spring.application.name=electricity-billing-backend

# ==========================
# Server
# ==========================

server.port=${PORT:8080}

# ==========================
# Database
# ==========================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# ==========================
# JWT
# ==========================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ==========================
# Email
# ==========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==========================
# Swagger
# ==========================

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================
# Logging
# ==========================

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.electricity.electricity_billing_backend=INFO

logging.file.name=logs/electricity-billing.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# ==========================
# Actuator
# ==========================

info.app.name=Electricity Billing System
info.app.version=1.0
info.app.description=Electricity Billing Management Backend
info.app.developer=Ashish Panwar

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Disable Mail Health Check (Fix Railway Healthcheck)
management.health.mail.enabled=false

server.forward-headers-strategy=framework
